name = "ChimeraMultipoles"
uuid = "b4a4ba4a-14dc-46a9-b63b-c0c44dc7c6da"
authors = ["lennoxkeeble <72128853+lennoxkeeble@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
PrecompileTools = "1.2.1"
StaticArrays = "1.9.15"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
